import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Map from '@/components/Map'
import Head from 'next/head'


const Home = () => {
  return (
    <>
    <Header />

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Map/>
      <Footer />
    </>
  )
}

export default Home