import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Map from '@/components/Map'
import Head from 'next/head'
import { useEffect } from 'react'

export const getServerSideProps = async () => {
  const about = await fetch(`${process.env.backend}/api/features?populate=*`)
    .then((res) => res.json())
    .then((res) => res.data)

  return {
    props: {
      about: about
    }
  }
}

const Home = ({ about }) => {
  useEffect(() => {
    console.log(about)
  }, [])
  return (
    <>
      <Header />

      <Head>
        <title>Аржааны Тувы</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Map arzhaans={about}/>
      <Footer />
    </>
  )
}

export default Home